### ISSUE TITLE
Error = Failed to retrive mp4 video url

### ISSUE THREAD

**Issue by nithintwobase** [superm0/HCVimeoVideoExtractor#13]
Some videos are getting error while playing videos. 
iOS version 15.6.1

error response : - Error = Failed to retrive mp4 video url
tried with both methods given in repo

**Comment by nivritgupta** [comment]
@nithintwobase  did you find any solutions?

**Comment by nyan-lin-tun** [comment]
@nithintwobase do you use `fetchVideoURLFrom(url: )` or `fetchVideoURLFrom(id: )` ?

**Comment by nithintwobase** [comment]
I tried both methods

**Comment by nyan-lin-tun** [comment]
for me using the `fetchVideoURLFrom(url: )` solved the issue

**Comment by nivritgupta** [comment]
@nithintwobase @nyan-lin-tun  Since yesterday this library stop working  (only for new videos) , old videos are working, they are already on Vimeo cloud) , I ll give you example. 

I checked the old videos JSON data and compare with the new video's JSON , check the screenshots. 

old Videos JSON data  in which we get the videos URL from this path **progressive**

<img width="1677" alt="Screen Shot 2022-10-02 at 21 07 21" src="https://user-images.githubusercontent.com/1904874/193498996-69303e1c-9f7b-48c3-b40c-fd48aefda0f0.png">


now if you upload a new video on Vimeo server and trying to get the JSON  using HCVimeoVideoExtractor  then you will find  **progressive** this key return empty data.

here is the screenshot 

 
<img width="1677" alt="Screen Shot 2022-10-02 at 21 07 46" src="https://user-images.githubusercontent.com/1904874/193499192-f7684be7-94b2-408c-b11d-1ae9c8167ac5.png">

**Comment by nithintwobase** [comment]
i get an error like this mentioned below.

Printing description of data:

▿ 3 elements

  ▿ 0 : 2 elements

    - key : "title"

    - value : Sorry

  ▿ 1 : 2 elements

    - key : "view"

    - value : 7

  ▿ 2 : 2 elements

    - key : "message"

    - value : This video does not exist.


but the same vimeo video work in Android & web


*Thanks & Regards,*

Nithin Shenoy s
Software Engineer

Mobile: +91 942 720 1284

Email: ***@***.***
Web: www.2basetechnologies.com



[image: Join 2base at Facebook]

[image: Join 2base at Twitter] <http://www.twitter.com/2basetech>

[image: Join 2base at LinkedIn]
<http://www.linkedin.com/companies/2base-technologies>

**Comment by nyan-lin-tun** [comment]
@nivritgupta seem there are some changes from the Vimeo

**Comment by RajaZahid** [comment]
@nithintwobase Did you get its solution. I am also facing same issue. Working fine for older videos but not for new videos.

**Comment by superm0** [comment]
this issue has been resolved with the latest update. for new Vimeo videos, the video URL can be retrieved through `.Quality1080p` or `.QualityUnknown`

**Comment by nivritgupta** [comment]
@superm0  the issue is not solved yet , I checked and trying to  retrieve the videos with .Quality1080p or .QualityUnknown only and found  this node from JSON still return  nil data , I am not sure why you close this issue. 

 progressive =         (
        );

**Comment by superm0** [comment]
@nivritgupta can you share your vimeo url?

**Comment by nivritgupta** [comment]
> @nivritgupta can you share your vimeo url?

Never mind the problem is fixed now , thanks
